import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/components/providers/provider";

export const metadata: Metadata = {
  title: "Code Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body >
        <Provider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          storageKey="code-studio-theme"
        >
          {children}
        </Provider>
      </body>
    </html>
  );
}
